num = int(input('Digite um número e veja a sua tabuada: '))
print('='*20)
print('{} x 1 é igual a: {}'.format(num, num*1))
print('{} x 2 é igual a: {}'.format(num, num*2))
print('{} x 3 é igual a: {}'.format(num, num*3))
print('{} x 4 é igual a: {}'.format(num, num*4))
print('{} x 5 é igual a: {}'.format(num, num*5))
print('{} x 6 é igual a: {}'.format(num, num*6))
print('{} x 7 é igual a: {}'.format(num, num*7))
print('{} x 8 é igual a: {}'.format(num, num*8))
print('{} x 9 é igual a: {}'.format(num, num*9))
print('{} x 10 é igual a: {}'.format(num, num*10))
print('='*20)