N = input('Digite alguma coisa: ')
print('O tipo primitivo desta palavra é ', type(N))
print('Essa palavra possuí espaços? ', N.isspace())
print('É um número? ', N.isnumeric())
print('É alfabética? ', N.isalpha())
print('É alfanúmerica? ', N.isalnum())
print('Está maiúscula? ', N.isupper())
print('Esta minuscula? ', N.islower())
print('Possui letra maiúscula? ', N.istitle())